dev:
  author.url: http://localhost:8080
  author.ip: http://127.0.0.1:8080
  author.login: admin
  author.password: admin
  login.token.name: login-token

  publish.url: http://localhost:8080
  publish.ip: http://127.0.0.1:8080
  publish.login: admin
  publish.password: admin
